# Generated by Django 5.0.7 on 2024-07-22 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=256)),
                ('course_code', models.CharField(max_length=256)),
                ('course_description', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Faculity',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('faculity_name', models.CharField(max_length=256)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('programme_label', models.CharField(max_length=60)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('semester_label', models.CharField(max_length=60)),
                ('semester_count', models.IntegerField()),
                ('date_start', models.DateTimeField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('session_label', models.CharField(max_length=60)),
                ('date_start', models.DateTimeField()),
                ('date_end', models.DateTimeField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('user_type', models.CharField(choices=[('student', 'Student'), ('staff', 'Staff')], max_length=8)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='StaffRole',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('role_label', models.CharField(max_length=60)),
                ('role_description', models.CharField(max_length=256)),
                ('roles', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='CourseCycle',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.course')),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.programme')),
                ('semster', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.semester')),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentsAssigned',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('assignment_description', models.TextField()),
                ('max_points_earnable', models.FloatField()),
                ('date_deadline', models.DateTimeField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('course_cycle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.coursecycle')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=256)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('faculity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.faculity')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('uuid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.user')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.staffrole')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('uuid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.user')),
                ('serial_no', models.CharField(max_length=10)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.department')),
                ('department_joined', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='api.department')),
                ('session_joined', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.session')),
            ],
        ),
        migrations.CreateModel(
            name='StudentGradesEarned',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('points_earned', models.FloatField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('course_cycle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.coursecycle')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.student')),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentsSubmissions',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('submission_description', models.TextField()),
                ('submission_date', models.DateTimeField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('assignments', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.assignmentsassigned')),
                ('course_cycle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.coursecycle')),
                ('points_earned', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.studentgradesearned')),
            ],
        ),
        migrations.CreateModel(
            name='TimeScheduleAssigned',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('time_slot', models.DateTimeField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('course_cycle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.coursecycle')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherAssigned',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('is_supervisor', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('course_cycle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.coursecycle')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.staff')),
            ],
        ),
        migrations.CreateModel(
            name='StudentEnrollment',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('course_cycle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.coursecycle')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.student')),
            ],
        ),
    ]
