# Generated by Django 5.0.7 on 2024-07-23 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.department'),
        ),
        migrations.AlterField(
            model_name='student',
            name='department_joined',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='api.department'),
        ),
        migrations.AlterField(
            model_name='student',
            name='session_joined',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.session'),
        ),
    ]
