# Generated by Django 5.0.7 on 2024-07-23 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_faculity_faculty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='session_created',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.session'),
        ),
    ]
