# Generated by Django 5.0.7 on 2024-07-24 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_faculty_session_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='session',
            field=models.ForeignKey(default='ab2bd2c0-9d82-49d9-b22a-59c697b8af88', on_delete=django.db.models.deletion.PROTECT, to='api.session'),
            preserve_default=False,
        ),
    ]
