# Generated by Django 5.0.7 on 2024-07-25 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_semester_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='date_end',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='date_end',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
