# Generated by Django 5.0.7 on 2024-07-29 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_user_middle_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignmentssubmissions',
            old_name='assignments',
            new_name='assignment',
        ),
        migrations.RemoveField(
            model_name='timescheduleassigned',
            name='time_slot',
        ),
        migrations.AddField(
            model_name='assignmentssubmissions',
            name='has_been_marked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='timescheduleassigned',
            name='time_end',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='timescheduleassigned',
            name='time_start',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='timescheduleassigned',
            name='weekday',
            field=models.IntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], null=True),
        ),
        migrations.AlterField(
            model_name='assignmentsassigned',
            name='date_deadline',
            field=models.DateTimeField(null=True),
        ),
    ]
