# Generated by Django 5.0.7 on 2024-08-17 12:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_session_programme'),
    ]

    operations = [
        migrations.AddField(
            model_name='programme',
            name='session_count',
            field=models.IntegerField(default=2),
        ),
        migrations.CreateModel(
            name='SchoolCalender',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_semester', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.semester')),
                ('current_session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.session')),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.programme')),
            ],
        ),
    ]
