# Generated by Django 5.0.7 on 2024-08-18 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_staff_role_staff_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentenrollment',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
