# Generated by Django 5.0.7 on 2024-08-21 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_studentenrollment_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_url',
            field=models.TextField(null=True),
        ),
    ]
