# Generated by Django 5.0.7 on 2024-08-26 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_session_session_code_alter_staff_staff_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='session_joined',
            field=models.ForeignKey(default='ab2bd2c0-9d82-49d9-b22a-59c697b8af88', on_delete=django.db.models.deletion.PROTECT, to='api.session'),
            preserve_default=False,
        ),
    ]
