# Generated by Django 5.0.7 on 2024-09-09 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_student_session_joined'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffrole',
            name='role_code',
        ),
        migrations.RemoveField(
            model_name='staffrole',
            name='roles',
        ),
        migrations.AddField(
            model_name='department',
            name='past_staff_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='department',
            name='past_student_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='staff',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.department'),
        ),
        migrations.AddField(
            model_name='staff',
            name='session_joined',
            field=models.ForeignKey(default='ab2bd2c09d8249d9b22a59c697b8af88', on_delete=django.db.models.deletion.PROTECT, to='api.session'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staffrole',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_id',
            field=models.CharField(max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(max_length=15, null=True, unique=True),
        ),
    ]
