# Generated by Django 5.0.7 on 2024-09-09 02:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_remove_staffrole_role_code_remove_staffrole_roles_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='session_joined',
        ),
        migrations.AddField(
            model_name='staff',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
