# Generated by Django 5.0.7 on 2024-09-12 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_remove_staff_session_joined_staff_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='allowed_departments',
            field=models.ManyToManyField(to='api.department'),
        ),
    ]
