# Generated by Django 5.0.7 on 2024-09-27 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_course_allowed_departments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semester',
            name='semester_label',
        ),
        migrations.RemoveField(
            model_name='session',
            name='session_code',
        ),
        migrations.RemoveField(
            model_name='staffrole',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='programme',
            name='programme_label',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='programme',
            name='session_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='schoolcalender',
            name='programme',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='api.programme'),
        ),
    ]
