# Generated by Django 5.0.7 on 2024-09-27 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_remove_semester_semester_label_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolcalender',
            name='current_session',
        ),
    ]
