# Generated by Django 5.0.7 on 2024-08-17 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0015_programme_session_count_schoolcalender'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassMeetings',
            fields=[
                ('course_cycle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.coursecycle')),
                ('mn', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserTokens',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.user')),
                ('token', models.CharField(max_length=256, null=True)),
            ],
        ),
    ]
